name: Build AmeOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ameos

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip \
            curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 openjdk-11-jdk repo

      - name: Initialize AOSP
        run: |
          mkdir -p $GITHUB_WORKSPACE/aosp
          cd $GITHUB_WORKSPACE/aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r75
          repo sync -c -j8

      - name: Copy AmeOS vendor tree
        run: cp -r $GITHUB_WORKSPACE/ameos/vendor/ameos $GITHUB_WORKSPACE/aosp/vendor/

      - name: Set up environment and build
        run: |
          cd $GITHUB_WORKSPACE/aosp
          source build/envsetup.sh
          lunch aosp_x86_64-eng
          make -j$(nproc) || make -j$(nproc)

      - name: Upload ROM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AmeOS-Build
          path: |
            $GITHUB_WORKSPACE/aosp/out/target/product/generic_x86_64/*.img
            $GITHUB_WORKSPACE/aosp/out/target/product/generic_x86_64/*.zip
